# Prebuilt rusty_v8 static libraries, one per system.
#
# `version` is the v8 crate version these archives belong to; flake.nix checks
# it against harness/core/Cargo.lock and refuses to evaluate when they drift.
# `targets` maps a Nix system to the Rust target triple the v8 build script
# puts in the archive name (its TARGET).
#
# x86_64-darwin is absent because nixpkgs 26.11 dropped the platform, not
# because rusty_v8 stopped shipping the archive.
#
# Regenerated by ./update-rusty-v8.py -- edit that, not this file.
{
  version = "150.3.0";

  targets = {
    "aarch64-darwin" = "aarch64-apple-darwin";
    "aarch64-linux" = "aarch64-unknown-linux-gnu";
    "x86_64-linux" = "x86_64-unknown-linux-gnu";
  };

  hashes = {
    "aarch64-darwin" = "sha256-UfWFt8OGkwYSn/1haKjwuJqNSjhw3LBwlgwrT9fQSCU=";
    "aarch64-linux" = "sha256-WR80+czoM+IAeYduyM4gsR0Y6jGk9BL0u6EQGB3ZdrY=";
    "x86_64-linux" = "sha256-2wl+bvpVp14L3oayuhl5g9CpG76DAfRVDEkNecB9evA=";
  };
}
