#!/usr/bin/env python3
"""Regenerate rusty-v8.nix for the v8 crate harness/core/Cargo.lock pins.

flake.nix refuses to evaluate once the pinned version and that lockfile
disagree, so this is the other half: it reads the wanted version out of the
mistral-vibe-src flake input, fetches each system's prebuilt archive, and
rewrites the pin with the hashes it got.

The archive URL mirrors what the v8 crate's build script would have fetched
had RUSTY_V8_ARCHIVE not been set -- see static_lib_url() there. Only the
target triple varies per system; `simdutf` is the one feature deno_core
enables, and the prebuilt profile is always release.

Exits 0 whether or not anything changed; `--check` exits 1 on a difference
instead of writing, for a CI job that only wants to know.
"""
import argparse
import json
import pathlib
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent
PIN = REPO / "rusty-v8.nix"
RELEASES = "https://github.com/denoland/rusty_v8/releases/download"

# Reads the v8 entry of the harness lockfile through the flake's own pin of
# mistral-vibe-src, so this and flake.nix can never consult different sources.
# The flake path is spelled out rather than left as ./., which would resolve
# against the caller's working directory instead of the repository.
LOCKED_VERSION_EXPR = """
let
  flake = builtins.getFlake "%s";
  lock = builtins.fromTOML
    (builtins.readFile "${flake.inputs.mistral-vibe-src}/harness/core/Cargo.lock");
in (builtins.head (builtins.filter (pkg: pkg.name == "v8") lock.package)).version
""" % REPO


def run(*argv: str) -> str:
    done = subprocess.run(argv, capture_output=True, text=True)
    if done.returncode != 0:
        sys.exit(f"{argv[0]} failed:\n{done.stderr.strip()}")
    return done.stdout.strip()


def archive_url(version: str, triple: str) -> str:
    return f"{RELEASES}/v{version}/librusty_v8_simdutf_release_{triple}.a.gz"


def prefetch_sri(url: str) -> str:
    base32 = run("nix-prefetch-url", "--type", "sha256", url)
    return run("nix", "hash", "convert", "--hash-algo", "sha256", "--to", "sri", base32)


def render(version: str, targets: dict, hashes: dict) -> str:
    def block(pairs):
        return "".join(
            '    "%s" = "%s";\n' % (key, pairs[key]) for key in sorted(pairs)
        )

    return f"""# Prebuilt rusty_v8 static libraries, one per system.
#
# `version` is the v8 crate version these archives belong to; flake.nix checks
# it against harness/core/Cargo.lock and refuses to evaluate when they drift.
# `targets` maps a Nix system to the Rust target triple the v8 build script
# puts in the archive name (its TARGET).
#
# x86_64-darwin is absent because nixpkgs 26.11 dropped the platform, not
# because rusty_v8 stopped shipping the archive.
#
# Regenerated by ./update-rusty-v8.py -- edit that, not this file.
{{
  version = "{version}";

  targets = {{
{block(targets)}  }};

  hashes = {{
{block(hashes)}  }};
}}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="report drift and exit 1 instead of rewriting the pin",
    )
    args = ap.parse_args()

    pinned = json.loads(
        run("nix", "eval", "--json", "--file", str(PIN), "--no-write-lock-file")
    )
    wanted = run(
        "nix", "eval", "--raw", "--impure", "--no-write-lock-file",
        "--expr", LOCKED_VERSION_EXPR,
    )

    targets = pinned["targets"]
    hashes = {t: prefetch_sri(archive_url(wanted, triple)) for t, triple in targets.items()}
    updated = render(wanted, targets, hashes)

    if updated == PIN.read_text():
        print(f"rusty-v8.nix is current (v8 {wanted}).")
        return 0

    print(f"v8 {pinned['version']} -> {wanted}")
    for system in sorted(targets):
        was, now = pinned["hashes"].get(system), hashes[system]
        print(f"  {system}: {'unchanged' if was == now else f'{was} -> {now}'}")

    if args.check:
        print("\nrusty-v8.nix is stale; run without --check to rewrite it.", file=sys.stderr)
        return 1

    PIN.write_text(updated)
    print(f"\nwrote {PIN.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
