name: Update Nix Flake

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3:00 AM
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Nix
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Update flake inputs
        run: nix flake update

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet flake.lock; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: Update flake.lock.'
          title: 'chore: Update flake.lock'
          body: |
            Automated flake.lock update.

            This PR updates the Nix flake inputs to their latest versions.
          branch: chore/auto-update-flake
          delete-branch: true
